# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)



1000.times do |i|
  Contact.create!(first_name: "#{i}_first_name", last_name: "#{i}_last_name", personal_email: "personal_email_#{i}", mobile_phone: "cellphone_#{i}")
end

AssessmentLevel.create!(level: "1")
AssessmentLevel.create!(level: "2")
AssessmentLevel.create!(level: "3")
AssessmentLevel.create!(level: "HR")
AssessmentLevel.create!(level: "MGR")

EventType.create(name: "OC Meeting")
EventType.create(name: "Protest - Solidarity")
EventType.create(name: "Protest - Our Union")
EventType.create(name: "Protest - Walkout")
EventType.create(name: "Union Day")

JobLevel.create(level: "1")
JobLevel.create(level: "2")
JobLevel.create(level: "3")
JobLevel.create(level: "4")
JobLevel.create(level: "5")
JobLevel.create(level: "6")
JobLevel.create(level: "7")
JobLevel.create(level: "8")
JobLevel.create(level: "10")
JobLevel.create(level: "11")
JobLevel.create(level: "12")
JobLevel.create(level: "99")

JobTitle.create(title: "HRBP")
JobTitle.create(title: "ICQA Programmer")
JobTitle.create(title: "Project Manager")
JobTitle.create(title: "Program Manager")
JobTitle.create(title: "SDE")
JobTitle.create(title: "SDE II")
JobTitle.create(title: "Sr. SDE")

SocialMediaType.create!(name: "dA")
SocialMediaType.create!(name: "Discord")
SocialMediaType.create!(name: "Facebook")
SocialMediaType.create!(name: "Mastodon")
SocialMediaType.create!(name: "Reddit")
SocialMediaType.create!(name: "Twitter")

Training.create(name: 'First Training')
Training.create(name: 'Second Training')
Training.create(name: 'Third Training')
Training.create(name: 'Fourth Training')
Training.create(name: 'Fifth Training')



Country.create(name: 'Afghanistan|AF')
Country.create(name: 'Ã…land Islands|AX')
Country.create(name: 'Albania|AL')
Country.create(name: 'Algeria|DZ')
Country.create(name: 'American Samoa|AS')
Country.create(name: 'Andorra|AD')
Country.create(name: 'Angola|AO')
Country.create(name: 'Anguilla|AI')
Country.create(name: 'Antarctica|AQ')
Country.create(name: 'Antigua and Barbuda|AG')
Country.create(name: 'Argentina|AR')
Country.create(name: 'Armenia|AM')
Country.create(name: 'Aruba|AW')
Country.create(name: 'Australia|AU')
Country.create(name: 'Austria|AT')
Country.create(name: 'Azerbaijan|AZ')
Country.create(name: 'Bahamas|BS')
Country.create(name: 'Bahrain|BH')
Country.create(name: 'Bangladesh|BD')
Country.create(name: 'Barbados|BB')
Country.create(name: 'Belarus|BY')
Country.create(name: 'Belgium|BE')
Country.create(name: 'Belize|BZ')
Country.create(name: 'Benin|BJ')
Country.create(name: 'Bermuda|BM')
Country.create(name: 'Bhutan|BT')
Country.create(name: '"Bolivia| Plurinational State of",BO')
Country.create(name: '"Bonaire| Sint Eustatius and Saba",BQ')
Country.create(name: 'Bosnia and Herzegovina|BA')
Country.create(name: 'Botswana|BW')
Country.create(name: 'Bouvet Island|BV')
Country.create(name: 'Brazil|BR')
Country.create(name: 'British Indian Ocean Territory|IO')
Country.create(name: 'Brunei Darussalam|BN')
Country.create(name: 'Bulgaria|BG')
Country.create(name: 'Burkina Faso|BF')
Country.create(name: 'Burundi|BI')
Country.create(name: 'Cambodia|KH')
Country.create(name: 'Cameroon|CM')
Country.create(name: 'Canada|CA')
Country.create(name: 'Cape Verde|CV')
Country.create(name: 'Cayman Islands|KY')
Country.create(name: 'Central African Republic|CF')
Country.create(name: 'Chad|TD')
Country.create(name: 'Chile|CL')
Country.create(name: 'China|CN')
Country.create(name: 'Christmas Island|CX')
Country.create(name: 'Cocos (Keeling) Islands|CC')
Country.create(name: 'Colombia|CO')
Country.create(name: 'Comoros|KM')
Country.create(name: 'Congo|CG')
Country.create(name: '"Congo| the Democratic Republic of the",CD')
Country.create(name: 'Cook Islands|CK')
Country.create(name: 'Costa Rica|CR')
Country.create(name: 'CÃ´te d\'Ivoire|CI')
Country.create(name: 'Croatia|HR')
Country.create(name: 'Cuba|CU')
Country.create(name: 'CuraÃ§ao|CW')
Country.create(name: 'Cyprus|CY')
Country.create(name: 'Czech Republic|CZ')
Country.create(name: 'Denmark|DK')
Country.create(name: 'Djibouti|DJ')
Country.create(name: 'Dominica|DM')
Country.create(name: 'Dominican Republic|DO')
Country.create(name: 'Ecuador|EC')
Country.create(name: 'Egypt|EG')
Country.create(name: 'El Salvador|SV')
Country.create(name: 'Equatorial Guinea|GQ')
Country.create(name: 'Eritrea|ER')
Country.create(name: 'Estonia|EE')
Country.create(name: 'Ethiopia|ET')
Country.create(name: 'Falkland Islands (Malvinas)|FK')
Country.create(name: 'Faroe Islands|FO')
Country.create(name: 'Fiji|FJ')
Country.create(name: 'Finland|FI')
Country.create(name: 'France|FR')
Country.create(name: 'French Guiana|GF')
Country.create(name: 'French Polynesia|PF')
Country.create(name: 'French Southern Territories|TF')
Country.create(name: 'Gabon|GA')
Country.create(name: 'Gambia|GM')
Country.create(name: 'Georgia|GE')
Country.create(name: 'Germany|DE')
Country.create(name: 'Ghana|GH')
Country.create(name: 'Gibraltar|GI')
Country.create(name: 'Greece|GR')
Country.create(name: 'Greenland|GL')
Country.create(name: 'Grenada|GD')
Country.create(name: 'Guadeloupe|GP')
Country.create(name: 'Guam|GU')
Country.create(name: 'Guatemala|GT')
Country.create(name: 'Guernsey|GG')
Country.create(name: 'Guinea|GN')
Country.create(name: 'Guinea-Bissau|GW')
Country.create(name: 'Guyana|GY')
Country.create(name: 'Haiti|HT')
Country.create(name: 'Heard Island and McDonald Islands|HM')
Country.create(name: 'Holy See (Vatican City State)|VA')
Country.create(name: 'Honduras|HN')
Country.create(name: 'Hong Kong|HK')
Country.create(name: 'Hungary|HU')
Country.create(name: 'Iceland|IS')
Country.create(name: 'India|IN')
Country.create(name: 'Indonesia|ID')
Country.create(name: '"Iran| Islamic Republic of",IR')
Country.create(name: 'Iraq|IQ')
Country.create(name: 'Ireland|IE')
Country.create(name: 'Isle of Man|IM')
Country.create(name: 'Israel|IL')
Country.create(name: 'Italy|IT')
Country.create(name: 'Jamaica|JM')
Country.create(name: 'Japan|JP')
Country.create(name: 'Jersey|JE')
Country.create(name: 'Jordan|JO')
Country.create(name: 'Kazakhstan|KZ')
Country.create(name: 'Kenya|KE')
Country.create(name: 'Kiribati|KI')
Country.create(name: '"Korea| Democratic People\'s Republic of",KP')
Country.create(name: '"Korea| Republic of",KR')
Country.create(name: 'Kuwait|KW')
Country.create(name: 'Kyrgyzstan|KG')
Country.create(name: 'Lao People\'s Democratic Republic|LA')
Country.create(name: 'Latvia|LV')
Country.create(name: 'Lebanon|LB')
Country.create(name: 'Lesotho|LS')
Country.create(name: 'Liberia|LR')
Country.create(name: 'Libya|LY')
Country.create(name: 'Liechtenstein|LI')
Country.create(name: 'Lithuania|LT')
Country.create(name: 'Luxembourg|LU')
Country.create(name: 'Macao|MO')
Country.create(name: '"Macedonia| the Former Yugoslav Republic of",MK')
Country.create(name: 'Madagascar|MG')
Country.create(name: 'Malawi|MW')
Country.create(name: 'Malaysia|MY')
Country.create(name: 'Maldives|MV')
Country.create(name: 'Mali|ML')
Country.create(name: 'Malta|MT')
Country.create(name: 'Marshall Islands|MH')
Country.create(name: 'Martinique|MQ')
Country.create(name: 'Mauritania|MR')
Country.create(name: 'Mauritius|MU')
Country.create(name: 'Mayotte|YT')
Country.create(name: 'Mexico|MX')
Country.create(name: '"Micronesia| Federated States of",FM')
Country.create(name: '"Moldova| Republic of",MD')
Country.create(name: 'Monaco|MC')
Country.create(name: 'Mongolia|MN')
Country.create(name: 'Montenegro|ME')
Country.create(name: 'Montserrat|MS')
Country.create(name: 'Morocco|MA')
Country.create(name: 'Mozambique|MZ')
Country.create(name: 'Myanmar|MM')
Country.create(name: 'Namibia|NA')
Country.create(name: 'Nauru|NR')
Country.create(name: 'Nepal|NP')
Country.create(name: 'Netherlands|NL')
Country.create(name: 'New Caledonia|NC')
Country.create(name: 'New Zealand|NZ')
Country.create(name: 'Nicaragua|NI')
Country.create(name: 'Niger|NE')
Country.create(name: 'Nigeria|NG')
Country.create(name: 'Niue|NU')
Country.create(name: 'Norfolk Island|NF')
Country.create(name: 'Northern Mariana Islands|MP')
Country.create(name: 'Norway|NO')
Country.create(name: 'Oman|OM')
Country.create(name: 'Pakistan|PK')
Country.create(name: 'Palau|PW')
Country.create(name: '"Palestine| State of",PS')
Country.create(name: 'Panama|PA')
Country.create(name: 'Papua New Guinea|PG')
Country.create(name: 'Paraguay|PY')
Country.create(name: 'Peru|PE')
Country.create(name: 'Philippines|PH')
Country.create(name: 'Pitcairn|PN')
Country.create(name: 'Poland|PL')
Country.create(name: 'Portugal|PT')
Country.create(name: 'Puerto Rico|PR')
Country.create(name: 'Qatar|QA')
Country.create(name: 'RÃ©union|RE')
Country.create(name: 'Romania|RO')
Country.create(name: 'Russian Federation|RU')
Country.create(name: 'Rwanda|RW')
Country.create(name: 'Saint BarthÃ©lemy|BL')
Country.create(name: '"Saint Helena| Ascension and Tristan da Cunha",SH')
Country.create(name: 'Saint Kitts and Nevis|KN')
Country.create(name: 'Saint Lucia|LC')
Country.create(name: 'Saint Martin (French part)|MF')
Country.create(name: 'Saint Pierre and Miquelon|PM')
Country.create(name: 'Saint Vincent and the Grenadines|VC')
Country.create(name: 'Samoa|WS')
Country.create(name: 'San Marino|SM')
Country.create(name: 'Sao Tome and Principe|ST')
Country.create(name: 'Saudi Arabia|SA')
Country.create(name: 'Senegal|SN')
Country.create(name: 'Serbia|RS')
Country.create(name: 'Seychelles|SC')
Country.create(name: 'Sierra Leone|SL')
Country.create(name: 'Singapore|SG')
Country.create(name: 'Sint Maarten (Dutch part)|SX')
Country.create(name: 'Slovakia|SK')
Country.create(name: 'Slovenia|SI')
Country.create(name: 'Solomon Islands|SB')
Country.create(name: 'Somalia|SO')
Country.create(name: 'South Africa|ZA')
Country.create(name: 'South Georgia and the South Sandwich Islands|GS')
Country.create(name: 'South Sudan|SS')
Country.create(name: 'Spain|ES')
Country.create(name: 'Sri Lanka|LK')
Country.create(name: 'Sudan|SD')
Country.create(name: 'Suriname|SR')
Country.create(name: 'Svalbard and Jan Mayen|SJ')
Country.create(name: 'Swaziland|SZ')
Country.create(name: 'Sweden|SE')
Country.create(name: 'Switzerland|CH')
Country.create(name: 'Syrian Arab Republic|SY')
Country.create(name: '"Taiwan| Province of China",TW')
Country.create(name: 'Tajikistan|TJ')
Country.create(name: '"Tanzania| United Republic of",TZ')
Country.create(name: 'Thailand|TH')
Country.create(name: 'Timor-Leste|TL')
Country.create(name: 'Togo|TG')
Country.create(name: 'Tokelau|TK')
Country.create(name: 'Tonga|TO')
Country.create(name: 'Trinidad and Tobago|TT')
Country.create(name: 'Tunisia|TN')
Country.create(name: 'Turkey|TR')
Country.create(name: 'Turkmenistan|TM')
Country.create(name: 'Turks and Caicos Islands|TC')
Country.create(name: 'Tuvalu|TV')
Country.create(name: 'Uganda|UG')
Country.create(name: 'Ukraine|UA')
Country.create(name: 'United Arab Emirates|AE')
Country.create(name: 'United Kingdom|GB')
Country.create(name: 'United States|US')
Country.create(name: 'United States Minor Outlying Islands|UM')
Country.create(name: 'Uruguay|UY')
Country.create(name: 'Uzbekistan|UZ')
Country.create(name: 'Vanuatu|VU')
Country.create(name: '"Venezuela| Bolivarian Republic of",VE')
Country.create(name: 'Viet Nam|VN')
Country.create(name: '"Virgin Islands| British",VG')
Country.create(name: '"Virgin Islands| U.S.",VI')
Country.create(name: 'Wallis and Futuna|WF')
Country.create(name: 'Western Sahara|EH')
Country.create(name: 'Yemen|YE')
Country.create(name: 'Zambia|ZM')
Country.create(name: 'Zimbabwe|ZW')

State.create(name: "Alabama", usps: "AL")
State.create(name: "Alaska", usps: "AK")
State.create(name: "Arizona", usps: "AZ")
State.create(name: "Arkansas", usps: "AR")
State.create(name: "California", usps: "CA")
State.create(name: "Colorado", usps: "CO")
State.create(name: "Connecticut", usps: "CT")
State.create(name: "Delaware", usps: "DE")
State.create(name: "District of Columbia", usps: "DC")
State.create(name: "Florida", usps: "FL")
State.create(name: "Georgia", usps: "GA")
State.create(name: "Hawaii", usps: "HI")
State.create(name: "Idaho", usps: "ID")
State.create(name: "Illinois", usps: "IL")
State.create(name: "Indiana", usps: "IN")
State.create(name: "Iowa", usps: "IA")
State.create(name: "Kansas", usps: "KS")
State.create(name: "Kentucky", usps: "KY")
State.create(name: "Louisiana", usps: "LA")
State.create(name: "Maine", usps: "ME")
State.create(name: "Maryland", usps: "MD")
State.create(name: "Massachusetts", usps: "MA")
State.create(name: "Michigan", usps: "MI")
State.create(name: "Minnesota", usps: "MN")
State.create(name: "Mississippi", usps: "MS")
State.create(name: "Missouri", usps: "MO")
State.create(name: "Montana", usps: "MT")
State.create(name: "Nebraska", usps: "NB*")
State.create(name: "*to NE in 1969")
State.create(name: "Nevada", usps: "NV")
State.create(name: "New Hampshire", usps: "NH")
State.create(name: "New Jersey", usps: "NJ")
State.create(name: "New Mexico", usps: "NM")
State.create(name: "New York", usps: "NY")
State.create(name: "North Carolina", usps: "NC")
State.create(name: "North Dakota", usps: "ND")
State.create(name: "Ohio", usps: "OH")
State.create(name: "Oklahoma", usps: "OK")
State.create(name: "Oregon", usps: "OR")
State.create(name: "Pennsylvania", usps: "PA")
State.create(name: "Puerto Rico", usps: "PR")
State.create(name: "Rhode Island", usps: "RI")
State.create(name: "South Carolina", usps: "SC")
State.create(name: "South Dakota", usps: "SD")
State.create(name: "Tennessee", usps: "TN")
State.create(name: "Texas", usps: "TX")
State.create(name: "Utah", usps: "UT")
State.create(name: "Vermont", usps: "VT")
State.create(name: "Virginia", usps: "VA")
State.create(name: "Washington", usps: "WA")
State.create(name: "West Virginia", usps: "WV")
State.create(name: "Wisconsin", usps: "WI")
State.create(name: "Wyoming", usps: "WY")
